/*
    Copyright (C) 2010 Collabora Ltd. <info@collabora.co.uk>
      @author George Kiagiadakis <george.kiagiadakis@collabora.co.uk>

    This library is free software; you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published
    by the Free Software Foundation; either version 2.1 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#include "init.h"
#include <glib-object.h>
#include "valuearray.h"

namespace QGlib {

namespace Private {
    void registerValueVTables();
    void registerWrapperConstructors(); //generated by codegen

    void registerValueVTables()
    {
        struct ValueVTable_ValueArray
        {
            //reads value and puts it in data
            static void get(const QGlib::Value & value, void *data)
            {
                GValueArray *array = static_cast<GValueArray *>(g_value_get_boxed(value));
                *reinterpret_cast<QGlib::ValueArray *>(data) = array;
            }

            // set applies data to value
            static void set(QGlib::Value & value, const void *data)
            {
                g_value_set_boxed(value, reinterpret_cast<const QGlib::ValueArray *>(data));
            };
        };

        QGlib::Value::registerValueVTable(QGlib::GetType<QGlib::ValueArray>(),
            QGlib::ValueVTable(ValueVTable_ValueArray::set, ValueVTable_ValueArray::get));
    }

}

void init()
{
    g_type_init();
    Private::registerValueVTables();
    Private::registerWrapperConstructors();
}

} //namespace QGlib
